In [2]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

for i in range(len(student1)):
    scores = student1[i] + student2[i]
    print(scores)
    print("===============")

144
170
164
167
177


In [3]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

student1 + student2

[69, 78, 72, 91, 85, 75, 92, 92, 76, 92]

In [5]:
import numpy as np
from numpy import ndarray
student1:ndarray = np.array([69, 78, 72, 91, 85])
student2:ndarray = np.array([75, 92, 92, 76, 92])

#可以做陣列運算,不需使用for...in
totols:ndarray= student1 + student2
for total in totols:
    print(total)
    print("=========")

144
170
164
167
177


In [6]:
array:ndarray = np.array([[1,2,3],[4,5,6]])
print(array)
#property
#ndim,shape,size,dtype

print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)


[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [7]:
np.random.randint(50,101,size=(50, 5))

array([[ 91,  60,  81,  94,  90],
       [ 60,  99,  59,  67,  70],
       [ 72,  77,  53,  73,  52],
       [ 84,  81,  68,  82,  73],
       [ 63,  54,  64,  97,  62],
       [ 60,  93,  88,  50,  51],
       [ 93,  54,  98,  78,  62],
       [ 92,  87,  99,  50,  70],
       [ 96,  71,  50,  56,  60],
       [ 54,  72,  68,  96,  98],
       [ 66,  70,  61,  68,  96],
       [ 81,  56,  95,  77,  55],
       [ 72,  86,  67,  71,  50],
       [ 50,  89,  66,  87,  92],
       [ 89,  70,  71,  70,  59],
       [ 99,  72,  80,  74,  52],
       [ 58,  93,  74,  86,  82],
       [ 58,  60,  54,  63,  54],
       [ 90,  89,  74,  78,  92],
       [ 77,  66,  96,  87,  56],
       [ 65,  53,  61,  89,  89],
       [ 71,  82,  85,  72,  60],
       [ 77,  73,  82,  76,  59],
       [ 69,  83,  85,  93,  99],
       [ 74,  51,  69,  99,  95],
       [ 81,  52,  58, 100,  77],
       [ 91,  95,  54,  76,  98],
       [ 69,  70,  86,  74,  92],
       [100,  87,  60,  53,  78],
       [ 60,  